# version: '3.8' (obsolete)
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: real_estate_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - real_estate_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_automation
    restart: always
    ports:
      - "5678:5678"
    environment:
      #      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      #      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_COOKIE_SAMESITE=none
      - N8N_SECURE_COOKIE=true
      - N8N_PROXY_HOPS=1
      #      - DB_TYPE=postgresdb
      #      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      #      - DB_POSTGRESDB_HOST=postgres
      #      - DB_POSTGRESDB_PORT=5432
      #      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      #      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_PROTOCOL=https
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GOOGLE_CLIENT_ID=${N8N_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${N8N_GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${N8N_GOOGLE_REDIRECT_URI}
      - TZ=Africa/Tunis
    volumes:
      - ${N8N_USER_DATA_PATH:-./data/n8n}:/home/node/.n8n
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    networks:
      - real_estate_network

  backend:
    build: ./backend
    container_name: FastAPI_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_WEB_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_WEB_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_WEB_REDIRECT_URI}
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT}
      - TZ=Africa/Tunis
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - OLLAMA_HOST=${OLLAMA_HOST:-host.docker.internal}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - real_estate_network

  frontend:
    build: ./frontend
    container_name: nuxt_ui
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - real_estate_network

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=embryologically-shrewd-may.ngrok-free.dev"
      - "--host-header=rewrite"
      - "n8n_automation:5678"
    ports:
      - "4040:4040"
    depends_on:
      - n8n
    networks:
      - real_estate_network

networks:
  real_estate_network:
    driver: bridge
