@startuml

actor ":SubAgent" as SubAgent
boundary ":PropertyManagementPage" as PropertyManagementPage
control ":PropertyController" as PropertyController
entity ":propertyModel" as propertyModel
entity ":visitModel" as visitModel
entity ":transactionRequest" as transactionRequest

ref over SubAgent, PropertyManagementPage, PropertyController, propertyModel: consult assigned properties

SubAgent -> PropertyManagementPage : requestTransactionApproval(client_id, price, dates)
activate PropertyManagementPage

PropertyManagementPage -> PropertyController : request_property_transaction(property_id, client_id, price, dates)
activate PropertyController

PropertyController -> propertyModel : get_by_id(property_id)
activate propertyModel
propertyModel --> PropertyController : return (property)

PropertyController -> transactionRequest : find_active_request(property_id)
activate transactionRequest
transactionRequest --> PropertyController : return (existing_request)

alt active request exists
    PropertyController --> PropertyManagementPage : alert ("the property is already requested")
else no active request exists
    PropertyController -> visitModel : find_finished_visit(property_id, client_id, agent_id)
    activate visitModel
    visitModel --> PropertyController : return (visit)
    deactivate visitModel

    alt visit is finished
        PropertyController --> PropertyManagementPage : alert ("the visit not completed")

        
    else visit is not finished
        PropertyController -> transactionRequest : create_transaction(property_id, agent_id, client_id, price, dates)
        transactionRequest --> PropertyController : return (true)
        deactivate transactionRequest

        PropertyController -> propertyModel : set_property_status(pending_status)
        propertyModel --> PropertyController : return (propert)
        deactivate propertyModel

        PropertyController --> PropertyManagementPage : return (propert)
    end
    PropertyManagementPage -> PropertyManagementPage : renderFinalizationResult()

end
deactivate PropertyController
deactivate PropertyManagementPage

@enduml
