@startuml

actor ":Client" as Client
boundary ":Telegram" as Telegram
boundary ":SmartAgent" as SmartAgent
control ":visits" as visits
entity ":visitModel" as visitModel

activate Telegram
Telegram -> SmartAgent : trigger_reminder_check()
activate SmartAgent

SmartAgent -> visits : get_upcoming_visits()
activate visits

visits -> visitModel : get_upcoming_visits()
activate visitModel
visitModel --> visits : return (upcoming_visits)

visits --> SmartAgent : return (upcoming_visits)

alt upcoming_visits is not empty
    loop for each upcoming visit
        
        SmartAgent -> SmartAgent : generate_message(upcoming_visit)
        
        SmartAgent -> Telegram : send_reminder(text)
        Client->Telegram: reads_reminder_message() 
        deactivate Telegram
        SmartAgent -> visits : mark_reminder_sent(visit_id)
        deactivate SmartAgent
        visits -> visitModel : get_by_id(visit_id)
        visitModel --> visits : return (visit)

        visits -> visits : set_reminder_sent (true)
        
        visits -> visitModel : save_reminded_visit()
        visitModel --> visits : return (true)
        deactivate visitModel
        
        deactivate visits
    end
end



@enduml
