@startuml

actor ":SubAgent" as SubAgent
boundary ":VisitManagementPage" as VisitManagementPage
control ":VisitsController" as VisitsController
entity ":visitModel" as visitModel

ref over SubAgent, VisitManagementPage, VisitsController, visitModel: view booked visits

SubAgent -> VisitManagementPage : searchAndFilterVisits(name, location, status, date_range)
activate VisitManagementPage

VisitManagementPage -> VisitManagementPage : filterVisitsLocally(name, location, status, date_range)

VisitManagementPage -> VisitManagementPage : renderFilteredVisits()
deactivate VisitManagementPage

@enduml
