@startuml

actor ":SubAgent" as SubAgent
boundary ":VisitManagementPage" as VisitManagementPage
control ":VisitsController" as VisitsController
entity ":visitModel" as visitModel

ref over SubAgent, VisitsController, visitModel: Authenticate

SubAgent -> VisitManagementPage : viewVisits()
activate VisitManagementPage

VisitManagementPage -> VisitsController : get_agent_visits_list(agent_id)
activate VisitsController

VisitsController -> visitModel : find_by_agent_id(agent_id)
activate visitModel
visitModel --> VisitsController : return (visits_list)
deactivate visitModel

VisitsController --> VisitManagementPage : return (visits_list)
deactivate VisitsController

VisitManagementPage -> VisitManagementPage : renderVisits(visits_list)
deactivate VisitManagementPage

@enduml
