@startuml

actor ":SubAgent" as SubAgent
boundary ":PropertyManagementPage" as PropertyManagementPage
control ":PropertyController" as PropertyController
entity ":propertyModel" as propertyModel

ref over SubAgent, PropertyManagementPage, PropertyController, propertyModel: consult assigned properties

SubAgent -> PropertyManagementPage : filterProperties(query, status)
activate PropertyManagementPage

PropertyManagementPage -> PropertyManagementPage : filterProperties(query, status)

PropertyManagementPage -> PropertyManagementPage : renderFilteredProperties()
deactivate PropertyManagementPage

@enduml
