@startuml


actor ":HeadAgent" as HeadAgent
boundary ":PropertyManagementPage" as PropertyManagementPage
control ":PropertyController" as PropertyController
control ":StorageService" as StorageService
entity ":propertyModel" as propertyModel

HeadAgent -> PropertyManagementPage : clickDeleteProperty(property_id)
activate PropertyManagementPage

PropertyManagementPage -> PropertyManagementPage : showConfirmationDialog()

alt confirm_deletion
    PropertyManagementPage -> PropertyController : delete_property(property_id)
    activate PropertyController
    
    opt property_has_images
        PropertyController -> StorageService : delete_all_images(property_id)
        activate StorageService
        StorageService --> PropertyController : return (true)
        deactivate StorageService
    end
    
    PropertyController -> propertyModel : remove_property(property_id)
    activate propertyModel
    propertyModel --> PropertyController : return (true)
    deactivate propertyModel
    
    PropertyController --> PropertyManagementPage : alert ("property deleted")
    deactivate PropertyController
    
    PropertyManagementPage -> PropertyManagementPage : closeDialog()
else cancel_deletion
    PropertyManagementPage -> PropertyManagementPage : closeDialog()
    deactivate PropertyManagementPage
end
@enduml