@startuml
autonumber

actor ":Client" as Client
boundary ":Telegram" as Telegram
boundary ":SmartAgent" as SmartAgent
control ":visits" as visits
control ":security" as security
entity ":visitModel" as visitModel

Client -> Telegram : request_reschedule()
activate Telegram

Telegram -> SmartAgent : process_message(text)
activate SmartAgent

SmartAgent -> visits : check_agent_availability(agent_id, new_date)
activate visits
visits -> visitModel : find_agent_visits(agent_id, new_date)
activate visitModel
visitModel --> visits : returns(visits_list)
deactivate visitModel
visits --> SmartAgent : returns(available_slots)
deactivate visits

SmartAgent --> Telegram : show_available_slots(available_slots)
deactivate SmartAgent
deactivate Telegram

Client -> Telegram : confirm_new_slot(slot)
activate Telegram

Telegram -> SmartAgent : process_message(text)
activate SmartAgent

SmartAgent -> visits : update_visit_db(original_visit_date, new_visit_date, property_id)
activate visits

visits -> security : encrypt_telegram_id(client_telegram_id)
activate security
security --> visits : returns(encrypted_chat_id)
deactivate security

visits -> visitModel : update_visit(original_visit_date, new_visit_date, property_id, encrypted_chat_id)
activate visitModel
visitModel --> visits : returns_true()
deactivate visitModel

visits --> SmartAgent : returns_true()
deactivate visits

SmartAgent --> Telegram : rescheduling_confirmation_msg
deactivate SmartAgent
deactivate Telegram
@enduml
