@startuml

actor ":HeadAgent" as HeadAgent

boundary ":PropertyManagementPage" as PropertyManagementPage
boundary ":PropertyEditModal" as PropertyModal
control ":PropertyController" as PropertyController
control ":StorageService" as StorageService
control ":OllamaEmbeddingModel" as OllamaEmbeddingModel
entity ":PropertyModel" as PropertyModel

ref over HeadAgent,PropertyManagementPage,PropertyModal,PropertyController,StorageService,OllamaEmbeddingModel,PropertyModel: view properties

HeadAgent -> PropertyManagementPage : clickEditProperty(property_id)
activate PropertyManagementPage

PropertyManagementPage -> PropertyModal : openEditModal(property_id)
activate PropertyModal
PropertyModal --> PropertyManagementPage : return (true)
deactivate PropertyManagementPage

HeadAgent -> PropertyModal : updatePropertyData(property_id, updated_data, new_coordinates, new_images, deleted_image_ids)

PropertyModal -> PropertyController : update_property(property_id, updated_data, new_coordinates, new_images, deleted_image_ids)
activate PropertyController

opt property_data_changed
    PropertyController -> OllamaEmbeddingModel : get_embedding(updated_data)
    activate OllamaEmbeddingModel
    OllamaEmbeddingModel --> PropertyController : return(embedding)
    deactivate OllamaEmbeddingModel
end

opt new_images_uploaded
    PropertyController -> StorageService : upload_images(new_images)
    activate StorageService
    StorageService --> PropertyController : return (image_urls)
end

opt images_deleted
    PropertyController -> StorageService : delete_image(deleted_image_ids)
    StorageService --> PropertyController : alert ("images deleted")
    deactivate StorageService
end

PropertyController -> PropertyModel : update_property_fields(property_id, updated_data, new_coordinates, embedding_description, image_urls, deleted_image_ids)
activate PropertyModel
PropertyModel --> PropertyController : return (true)
deactivate PropertyModel

PropertyController --> PropertyModal : return (true)
deactivate PropertyController
PropertyModal -> PropertyModal : close()
deactivate PropertyModal

@enduml
