@startuml

actor ":HeadAgent" as HeadAgent
boundary ":InquiriesPage" as InquiriesPage
control ":VisitsController" as VisitsController
entity ":transactionRequest" as transactionRequest
entity ":propertyModel" as propertyModel
control ":emailService" as emailService

ref over HeadAgent, InquiriesPage, VisitsController, transactionRequest: Authenticate

HeadAgent -> InquiriesPage : viewInquiries()
activate InquiriesPage

InquiriesPage -> VisitsController : get_pending_inquiries(agent_id)
activate VisitsController

VisitsController -> transactionRequest : get_pending_detailed(agent_id)
activate transactionRequest
transactionRequest --> VisitsController : return (inquiries_list)

VisitsController --> InquiriesPage : return (inquiries_list)
deactivate VisitsController

InquiriesPage -> InquiriesPage : renderInquiries(inquiries_list)

alt action is "approve"
    HeadAgent -> InquiriesPage : approveRequest(inquiry_id)
    
    InquiriesPage -> VisitsController : update_inquiry_status(inquiry_id, status="replied")
    activate VisitsController
    
    VisitsController -> transactionRequest : get_by_id(inquiry_id)
    transactionRequest --> VisitsController : return (inquiry)

    VisitsController -> transactionRequest : update_status(inquiry_id, "approved")
    transactionRequest --> VisitsController : return (true)

    VisitsController -> propertyModel : set_property_status(property_id, "approved_sold/approved_rent")
    activate propertyModel
    propertyModel --> VisitsController : return (property)

    VisitsController -> emailService : send_client_transaction_success_email()
    activate emailService
    deactivate emailService
    
    VisitsController --> InquiriesPage : alert  ("transaction approved")


else action is "refuse"
    HeadAgent -> InquiriesPage : refuseRequest(inquiry_id)
    
    InquiriesPage -> VisitsController : update_inquiry_status(inquiry_id, status="closed")

    VisitsController -> transactionRequest : get_by_id(inquiry_id)
    transactionRequest --> VisitsController : return (inquiry)

    VisitsController -> transactionRequest : update_status(inquiry_id, "rejected")
    transactionRequest --> VisitsController : return (true)
    deactivate transactionRequest
    
    VisitsController -> propertyModel : set_property_status(property_id, "available")
    propertyModel --> VisitsController : return (property)
    deactivate propertyModel

    VisitsController -> emailService : send_transaction_rejection_email()
    activate emailService
    deactivate emailService
    
    VisitsController --> InquiriesPage : alert  ("transaction rejected")
    deactivate VisitsController
    
end

deactivate InquiriesPage

@enduml
