@startuml

actor ":Admin" as ActorAdmin

boundary ":AdminDashboard" as AdminDashboard
control ":UserController" as UserController
entity ":UserModel" as UserModel

ref over ActorAdmin,UserController ,UserModel: view users

ActorAdmin -> AdminDashboard : toggleStatus() 
activate AdminDashboard 

AdminDashboard -> UserController : toggle_user_status(staff_user_id)
activate UserController

UserController -> UserModel : get_by_id(staff_user_id)
activate UserModel
UserModel --> UserController : return (staff_user)

UserController -> UserModel : toggle_active_status(staff_user)
UserModel --> UserController : return (staff_user_toggled_status)
deactivate UserModel 

UserController --> AdminDashboard : return (staff_user_toggled_status)
deactivate UserController 
AdminDashboard -> AdminDashboard : render_staff_listing(staff_user_toggled_status) 

deactivate AdminDashboard

@enduml
