@startuml

actor ":SubAgent" as SubAgent
boundary ":VisitManagementPage" as VisitManagementPage
control ":VisitsController" as VisitsController
entity ":visitModel" as visitModel

ref over SubAgent, VisitManagementPage, VisitsController, visitModel: view booked visits 

SubAgent -> VisitManagementPage : clickUpdateStatus(visit_id, status)
activate VisitManagementPage

VisitManagementPage -> VisitsController : update_visit_status(visit_id, status)
activate VisitsController

VisitsController -> visitModel : get_with_property_and_owner(visit_id)
activate visitModel
visitModel --> VisitsController : return (visit)


VisitsController -> visitModel : update_status(visit_id, status)
visitModel --> VisitsController : return (visit)
deactivate visitModel

VisitsController --> VisitManagementPage : return (visit)
deactivate VisitsController

VisitManagementPage -> VisitManagementPage : renderVisits()
deactivate VisitManagementPage

@enduml
