@startuml


actor ":HeadAgent" as HeadAgent
boundary ":PropertyManagementPage" as PropertyManagementPage
boundary ":PropertyAddModal" as PropertyModal
control ":PropertyController" as PropertyController
control ":StorageService" as StorageService
control ":OllamaEmbeddingModel" as OllamaEmbeddingModel
entity ":propertyModel" as propertyModel

HeadAgent -> PropertyManagementPage : clickAddProperty()
activate PropertyManagementPage

PropertyManagementPage -> PropertyModal : openAddModal()
activate PropertyModal
PropertyManagementPage <-- PropertyModal : return (true)
deactivate PropertyManagementPage

HeadAgent -> PropertyModal : submitPropertyData(property_data, coordinates, images)

PropertyModal -> PropertyController : create_property(property_data, coordinates, images)
activate PropertyController

PropertyController -> OllamaEmbeddingModel : get_embedding(property_data)
activate OllamaEmbeddingModel
OllamaEmbeddingModel --> PropertyController : return (embedding_description)
deactivate OllamaEmbeddingModel

PropertyController -> StorageService : upload_image(images)
activate StorageService
StorageService --> PropertyController : return ( images_urls)
deactivate StorageService

PropertyController -> propertyModel : save_property(property_data, coordinates, embedding_description, images_urls)
activate propertyModel
propertyModel --> PropertyController : return (true)
deactivate propertyModel

PropertyController --> PropertyModal : return (true)
deactivate PropertyController

PropertyModal -> PropertyModal : close()
deactivate PropertyModal
@enduml
