@startuml

actor ":Admin" as ActorAdmin
boundary ":AdminDashboard" as AdminDashboard
boundary ":CreateStaffModal" as CreateStaffModal
control ":UserController" as UserController
entity ":UserModel" as UserModel

ref over ActorAdmin,UserController ,UserModel: view users

ActorAdmin -> AdminDashboard : clickCreateStaff()
activate AdminDashboard

AdminDashboard -> CreateStaffModal : open()
deactivate AdminDashboard

activate CreateStaffModal

ActorAdmin -> CreateStaffModal : selectRole(role)

alt role == "sub_agent"
    CreateStaffModal -> UserController : get_head_agents()
    activate UserController

    UserController -> UserModel : get_head_agents()
    activate UserModel
    UserModel --> UserController : return(head_agents)

    UserController --> CreateStaffModal : return (head_agents)

    CreateStaffModal -> CreateStaffModal : render_head_agents_dropdown(head_agents)
    ActorAdmin -> CreateStaffModal : selectHeadAgent(head_agent)
end

ActorAdmin -> CreateStaffModal : submitStaffForm(name, email,phone_number, role, head_agent_id)

CreateStaffModal -> UserController : create_user_admin(name, email,phone_number, role, head_agent_id)

UserController -> UserModel : get_by_email(email)
alt email_already_exists

    UserModel --> UserController : return (false)
    UserController --> CreateStaffModal : alert("Email already registered")
    
else email_is_new
    UserModel --> UserController : return (true)
    UserController -> UserController : hash_password(password)
    UserController -> UserModel : create(name, email,phone_number , role, head_agent_id)
    UserModel --> UserController : return (true)
    deactivate UserModel
    
    UserController --> CreateStaffModal : return (true)
    deactivate UserController
    

    deactivate AdminDashboard 
    CreateStaffModal -> CreateStaffModal : close()
end
deactivate CreateStaffModal

@enduml