@startuml

actor ":HeadAgent" as HeadAgent
boundary ":PropertyManagementPage" as PropertyManagementPage
control ":PropertyController" as PropertyController
entity ":propertyModel" as propertyModel
ref over HeadAgent,PropertyManagementPage,PropertyController,propertyModel:authenticate
HeadAgent -> PropertyManagementPage : viewProperties()
activate PropertyManagementPage
PropertyManagementPage -> PropertyController : get_agent_properties(agent_id)
activate PropertyController
PropertyController -> propertyModel : find_by_agent_id(agent_id)
activate propertyModel
propertyModel --> PropertyController : return (properties_list)
deactivate propertyModel
PropertyController --> PropertyManagementPage : return (properties_list)
deactivate PropertyController
PropertyManagementPage -> PropertyManagementPage : renderPropertiesList()
deactivate PropertyManagementPage
@enduml
