@startuml


actor ":Client" as Client
boundary ":Telegram" as Telegram
boundary ":SmartAgent" as SmartAgent
control ":visits" as visits
entity ":userModel" as userModel
entity ":visitModel" as visitModel

Client -> Telegram : request_visit()
activate Telegram

Telegram -> SmartAgent : send_message(text)
activate SmartAgent

SmartAgent -> visits : check_agent_availability(agent_id, dateTime)
activate visits
visits -> visitModel : find_agent_visits(agent_id, dateTime)
activate visitModel
visitModel --> visits : returns(visits_list)
visits --> SmartAgent : returns(available_slots)
SmartAgent -> SmartAgent : generate_message(available_slots)


SmartAgent -> Telegram : show_available_slots(text)

Client -> Telegram : confirm_slot()

Telegram -> SmartAgent : send_message(text)

SmartAgent -> visits : book_visit(property_id, client_telegram_chat_id, dateTime, agent_id)

visits -> visits : encrypt_telegram_chat_id(client_telegram_chat_id)


visits -> userModel : get_by_telegram_chat_id(encrypted_telegram_chat_id)
activate userModel
userModel --> visits : return (user)
deactivate userModel

visits -> visitModel : save_visit(property_id, encrypted_telegram_chat_id, dateTime, agent_id)
visitModel --> visits : return (dateTime)
deactivate visitModel

visits --> SmartAgent : return (dateTime)
deactivate visits
SmartAgent -> SmartAgent : generate_message (dateTime)
SmartAgent -> Telegram : send_confirmation_message(text)
deactivate SmartAgent
deactivate Telegram
@enduml
