@startuml


actor ":Client" as Client
boundary ":Telegram" as Telegram
boundary ":SmartAgent" as SmartAgent
control ":visits" as visits
entity ":visitModel" as visitModel

Client -> Telegram : request_reschedule()
activate Telegram

Telegram -> SmartAgent : process_message(text)
activate SmartAgent

SmartAgent -> visits : check_agent_availability(agent_id, new_dateTime)
activate visits
visits -> visitModel : find_agent_visits(agent_id, new_dateTime)
activate visitModel
visitModel --> visits : return (visits_list)

visits --> SmartAgent : return (available_slots)
SmartAgent -> SmartAgent : generate_message (available_slots)

SmartAgent --> Telegram : show_available_slots(text)

Client -> Telegram : confirm_new_slot()

Telegram -> SmartAgent : send_message(text)

SmartAgent -> visits : update_visit(original_visit_dateTime, new_visit_dateTime, property_id)

visits -> visits : encrypt_sequence diagram schedule visit(client_telegram_chat_id)

visits -> visitModel : update_visit(original_visit_dateTime, new_visit_dateTime, property_id, encrypted_telegram_chat_id)
visitModel --> visits : return (new_visit_dateTime)
deactivate visitModel

visits --> SmartAgent : return (new_visit_dateTime)

deactivate visits
SmartAgent -> SmartAgent : generate_message (new_visit_dateTime)
SmartAgent -> Telegram : send_confirmation_msg(text)
deactivate SmartAgent
deactivate Telegram
@enduml
