@startuml


actor ":User" as ActorUser

boundary ":LoginPage" as LoginPage
control ":AuthController" as AuthController
entity ":UserModel" as UserModel

ref over ActorUser,LoginPage ,AuthController,UserModel: register

ActorUser -> LoginPage : handleLogin()
activate LoginPage

LoginPage -> AuthController : login(username, password)
activate AuthController

AuthController -> UserModel : get_by_email(username, password)
activate UserModel
UserModel --> AuthController : return(user)
deactivate UserModel

AuthController -> AuthController : verify_password(password, hashed_password)

alt  invalid_credentials

    AuthController --> LoginPage : alert("Incorrect email or password")

else credentials_valid
    
    alt user.is_active == false
    
        AuthController --> LoginPage : alert("Account deactivated")
        

    else user.is_active == true
    
        AuthController -> AuthController : create_access_token()
        AuthController ->  LoginPage: recieve_jwt_token(token)

        deactivate AuthController
        alt user.role == 'admin'
            LoginPage -> LoginPage : navigateTo('/admin')
            
        else user.role == 'head_agent'
            LoginPage -> LoginPage : navigateTo('/agency')
            
        else user.role == 'sub_agent'
            LoginPage -> LoginPage : navigateTo('/agent')
            
        else user.role == 'client'
            LoginPage -> LoginPage : navigateTo('/home_page')
            
        end
        
        deactivate LoginPage
        
    end
    
    
    

end

@enduml

