@startuml
autonumber

actor ":Client" as Client
boundary ":PropertyDetailsPage" as PropertyDetailsPage
boundary ":Telegram" as Telegram
control ":SmartAgent" as SmartAgent
control ":PropertyController" as PropertyController
control ":OllamaEmbeddingModel" as OllamaEmbeddingModel
entity ":propertyModel" as propertyModel
entity ":pgvector" as pgvector

Client -> PropertyDetailsPage : handleTelegramInquiry()
activate PropertyDetailsPage

alt telegram_paired == false
    ref over Client, PropertyDetailsPage, SmartAgent : 	 telegram paire
    deactivate PropertyDetailsPage
else telegram_paired == true
    PropertyDetailsPage -> Telegram : openTelegramBot(start_command)
    deactivate PropertyDetailsPage
    
    activate Telegram
    
    Telegram -> SmartAgent : send_query(chat_id, query)
    activate SmartAgent
    
    SmartAgent -> PropertyController : rag_search(query)
    activate PropertyController
    
    PropertyController -> OllamaEmbeddingModel : get_query_embedding(query)
    activate OllamaEmbeddingModel
    
    alt ollama_unavailable
        OllamaEmbeddingModel --> PropertyController : returns_false()
        
        PropertyController --> SmartAgent : alert("ollama unavailbale")
        deactivate PropertyController
        SmartAgent --> Telegram : ErrorMessage("ollama unavailbale")
        deactivate SmartAgent
        deactivate Telegram
    else embedding_generated
        OllamaEmbeddingModel --> PropertyController : embedding
        deactivate OllamaEmbeddingModel
        
        PropertyController -> propertyModel : get_properties(embedding)
        activate propertyModel
        
        propertyModel -> pgvector : searchWith_l2_distance(embedding)
        activate pgvector
        pgvector --> propertyModel : return_properties(embedding)
        deactivate pgvector
        
        propertyModel --> PropertyController : return_properties(embedding)
        deactivate propertyModel
        
        PropertyController --> SmartAgent : RAGresponse(context)
        deactivate PropertyController
        
        SmartAgent --> Telegram : response_message(text)
        deactivate SmartAgent
        deactivate Telegram
    end
end
@enduml
